services:
  la27web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5174:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
    environment:
      - NODE_ENV=development